version: '3'

services:
  neo4j:
    image: neo4j:4.4.25
    environment:
      NEO4J_AUTH: neo4j/dadalakun25
    ports:
      - "7687:7687" # Neo4j Bolt
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs

  goserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=dadalakun25
    depends_on:
      - neo4j